# This file was generated by GoReleaser. DO NOT EDIT.
cask "nib" do
  version "0.0.20"

  on_macos do
    on_arm do
      sha256 "5bf2d336eeaec5a5df2d62dd8ceaeda7f7a5f97400f49a2ff07c982536e8ff4c"
      url "https://github.com/bricejulia/nib/releases/download/v#{version}/nib_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d922974a6e4b5b5bf929473ca910535e90dcd7adf8313b770c594773fa82adbf"
      url "https://github.com/bricejulia/nib/releases/download/v#{version}/nib_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "020e40fec4419afadf15b63b4c19f77cfd68547cccfe352a8ba99c3ef3de28b8"
      url "https://github.com/bricejulia/nib/releases/download/v#{version}/nib_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a093175706bec6fa6c15128aa9aa1ffa264e9e87403e40af7ae837bb98fb8275"
      url "https://github.com/bricejulia/nib/releases/download/v#{version}/nib_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nib"
  desc "A terminal code editor in Go. Modal editing in the vim tradition, real syntax awareness from tree-sitter, and real semantic features from language servers"
  homepage "https://github.com/bricejulia/nib"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nib"

  # No zap stanza required
end
