# This file was generated by GoReleaser. DO NOT EDIT.
cask "nib" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "93eccbeb5b9bd3af43237c2416e0b2feee9745ebec7241f605bc35bbbeef9d54"
      url "https://github.com/bricejulia/nib/releases/download/v#{version}/nib_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b6e479690e1ea9d3ee2b79a0cada24aff8b8d0d86e6606277a5030e48d4df5b"
      url "https://github.com/bricejulia/nib/releases/download/v#{version}/nib_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a8c10fd48260d4504845d5aeb3aad3042855c88062fd134ad3117dfd73e0d978"
      url "https://github.com/bricejulia/nib/releases/download/v#{version}/nib_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "30ac614e822e83090991666ec3b912125ccdf7f406d17d7818c9ddc5bd690cf5"
      url "https://github.com/bricejulia/nib/releases/download/v#{version}/nib_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nib"
  desc "A terminal code editor in Go. Modal editing in the vim tradition, real syntax awareness from tree-sitter, and real semantic features from language servers"
  homepage "https://github.com/bricejulia/nib"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nib"

  # No zap stanza required

end
