# This file was generated by GoReleaser. DO NOT EDIT.
cask "nib" do
  version "0.0.10"

  on_macos do
    on_arm do
      sha256 "fdd74f8bb5bae3f7cfb2e967449c7bc436e7de839aac59bc907824af6811887c"
      url "https://github.com/bricejulia/nib/releases/download/v#{version}/nib_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e742600de9efdd3deceb36c699cb172f26fe30a1f0e3d0c2de6524afecd1575a"
      url "https://github.com/bricejulia/nib/releases/download/v#{version}/nib_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "172d12a92f022e64b7588b5e5b455d4c6b25506ab8c90e1fb318ca5d6ee60ab1"
      url "https://github.com/bricejulia/nib/releases/download/v#{version}/nib_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e62d30285069589241bf7568582363dba5f760a01894afe5afd1236a42fe2396"
      url "https://github.com/bricejulia/nib/releases/download/v#{version}/nib_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nib"
  desc "A terminal code editor in Go. Modal editing in the vim tradition, real syntax awareness from tree-sitter, and real semantic features from language servers"
  homepage "https://github.com/bricejulia/nib"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nib"

  # No zap stanza required
end
