# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailspin" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "914ede0ec2fc3e625a939c443596291350b8973943c63fd51cc6fef963e8ce67"
      url "https://github.com/bricejulia/tailspin/releases/download/v#{version}/tailspin_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d48e6e7250bcc3cf2ba584c0eead27e3f7a58cc1dcd9babf8d56ef5409d614a9"
      url "https://github.com/bricejulia/tailspin/releases/download/v#{version}/tailspin_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b86e2cb5538955552f9f9a3e5b0a834a8baf62d6fd21ab683e31878c7d4cfb9d"
      url "https://github.com/bricejulia/tailspin/releases/download/v#{version}/tailspin_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "075edbd0338b07a6d9f3e422d6650ae49858cc0ad6943ba9a075fae9cbe5742a"
      url "https://github.com/bricejulia/tailspin/releases/download/v#{version}/tailspin_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tailspin"
  desc "Browse, filter, and live-tail gcp log entries for a project without leaving the terminal — no `gcloud logging read` incantations, no Cloud Console tab."
  homepage "https://github.com/bricejulia/tailspin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailspin"

  # No zap stanza required
end
