# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailspin" do
  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "3c111bb38ee8dce7b38459432fb5ae88353e339194287b4c5e1f03bd38bd8b86"
      url "https://github.com/bricejulia/tailspin/releases/download/v#{version}/tailspin_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "520798c2ae0fcc4c54689a0b186c832e3cd84ea12434d52139b002684a05592d"
      url "https://github.com/bricejulia/tailspin/releases/download/v#{version}/tailspin_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "13948a5b1453438ad3fc2d835025f1960808c6b3d7da2eef4a0fa672534424bc"
      url "https://github.com/bricejulia/tailspin/releases/download/v#{version}/tailspin_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "abd8a557bfd89bcf7be0e8e7ea3faac71c5c1ae0c1530166a9afe8d8584ffa1c"
      url "https://github.com/bricejulia/tailspin/releases/download/v#{version}/tailspin_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tailspin"
  desc "Browse, filter, and live-tail gcp log entries for a project without leaving the terminal — no `gcloud logging read` incantations, no Cloud Console tab."
  homepage "https://github.com/bricejulia/tailspin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailspin"

  # No zap stanza required
end
