# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailspin" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "0d71bed901a94a61555e97de5760321a337ca92dfce185d2a3ef332c7732f5be"
      url "https://github.com/bricejulia/tailspin/releases/download/v#{version}/tailspin_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "547fb062a17f51d57fbd82e06717fa2aaee587e644c52c574e417ff12208572a"
      url "https://github.com/bricejulia/tailspin/releases/download/v#{version}/tailspin_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2b6bd890c813309ea3df32d3584b037938f2b54e0c86d099ae571acb14ec17d5"
      url "https://github.com/bricejulia/tailspin/releases/download/v#{version}/tailspin_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e88a39af2882ad3b6d6d8b2d16719d0a58aff93bf04cb0cbf16969910ffcaf41"
      url "https://github.com/bricejulia/tailspin/releases/download/v#{version}/tailspin_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tailspin"
  desc "Browse, filter, and live-tail gcp log entries for a project without leaving the terminal — no `gcloud logging read` incantations, no Cloud Console tab."
  homepage "https://github.com/bricejulia/tailspin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailspin"

  # No zap stanza required
end
